highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: https://xyz-han.github.io
author: Thor Odinson

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Xiangyu Han's Resume
name: Xiangyu Han
email: xyhan AT smail DOT nju DOT edu DOT cn
email_full: xyhan@smail.nju.edu.cn
website: xyz-han.github.io
website_full: https://xyz-han.github.io

google_maps: 'https://maps.app.goo.gl/7SSrWxM9mkybGVBcA'
address:
  postcode: 210023
  city: Nanjing
  country: China

# needed for travis-ci build
exclude: [vendor]
